server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Tự động tạo route dựa trên Service ID (tùy chọn)
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE  # Tên service đăng ký trên Eureka
          predicates:
            - Path=/users/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
  application:
    name: api-gateway
flyway:
  enabled: true
  locations: classpath:db/migration
  baseline-on-migrate: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka