server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/ecommerce
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Tự động tạo route dựa trên Service ID (tùy chọn)
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE  # Tên service đăng ký trên Eureka
          predicates:
            - Path=/users/**
        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/identity/**
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notifications/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
  application:
    name: api-gateway
flyway:
  enabled: true
  locations: classpath:db/migration
  baseline-on-migrate: true
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh