spring:
  application:
    name: seller-service
  datasource:
    url: jdbc:postgresql://postgres:5432/seller_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8086

eureka:
  client:
    enabled: false

logging:
  level:
    com.example.sellerservice: DEBUG
    org.springframework.web: INFO

