spring:
  application:
    name: product-service

  # Kafka Producer
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        spring.json.add.type.headers: false

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    prefer-ip-address: true

# Kafka topic config
app:
  kafka:
    topic:
      product-events: product-events

logging:
  level:
    com.example.productservice: DEBUG
    org.springframework.web: INFO

