spring:
  application:
    name: product-service

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    com.example.productservice: DEBUG
    org.springframework.web: INFO

