spring:
  application:
    name: discount-service
  cloud:
    config:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7080/realms/ecommerce

server:
  port: 8091

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    com.example.discountservice: DEBUG
    org.springframework.web: INFO
